on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: denoland/setup-deno@11b63cf76cfcafb4e43f97b6cad24d8e8438f62d # v1.5.2
      - run: make lint
      - run: make test
        env:
          BACKPORTER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BACKPORTER_GITEA_FORK: GiteaBot/gitea
          BACKPORTER_GITHUB_SECRET: dummy
          BACKPORTER_REPO: go-gitea/gitea
